model_path: /mnt/deeplink/group01/deeplink-test/weight
resource_path: /nvme/qa_test_models/resource
dst_path: /nvme/qa_test_models/autotest_model
log_path: /test/log
benchmark_path: /nvme/qa_test_models/benchmark-reports
dataset_path: /nvme/qa_test_models/datasets/ShareGPT_V3_unfiltered_cleaned_split.json
env_tag: A2

tp_config:
    Qwen2.5-32B-Instruct: 2
    Qwen3-32B: 2
    Qwen3-30B-A3B-Instruct: 2

pytorch_chat_model:
    - /Qwen3-0.6B
    - /Qwen3-32B
    - /Qwen2.5-32B-Instruct
    - /Qwen3-30B-A3B-Instruct


pytorch_vl_model:
    - empty


pytorch_base_model:
    - empty


pytorch_quatization:
    awq:
        - empty
    w8a8:
        - empty
    no_kvint4:
        - empty
    no_kvint8:
        - empty

longtext_model:
    - empty

benchmark_model:
    - /Qwen3-0.6B
    - /Qwen2.5-32B-Instruct
